name: "Create a new author bio"
description: "Submit this form to automatically create a new author bio"
title: "[New Author] "
labels: ["Author Bio Creation"]
body:
  - type: input
    id: author_name
    attributes:
      label: "Author Name"
      description: "Full name of the author"
      placeholder: "Jane Doe"
    validations:
      required: true
  
  - type: input
    id: author_role
    attributes:
      label: "Author Role"
      description: "Professional title or role"
      placeholder: "Senior Software Engineer"
    validations:
      required: false
  
  - type: textarea
    id: author_bio
    attributes:
      label: "Author Bio"
      description: "Short biography (1-3 paragraphs)"
      placeholder: "Jane is a software engineer with 10 years of experience..."
    validations:
      required: false
  
  - type: textarea
    id: author_picture
    attributes:
      label: "Author Picture"
      description: |
        Attach a bio picture if you have one. The image will be renamed to match the author's name.
        
        **Instructions:**
        1. Click in this field
        2. Drag and drop an image or click to select a file
        3. Wait for the upload to complete (you'll see a preview)
        
        Image requirements:
        - Square or portrait orientation recommended
        - Professional headshot preferred
        - Clear, high-quality image
        
        Note: The uploaded image will be automatically renamed to match the author's name.
      placeholder: |
        Drag and drop your image file here
    validations:
      required: true
  
  - type: input
    id: github_username
    attributes:
      label: "GitHub Username"
      description: "GitHub username (without @)"
      placeholder: "janedoe"
    validations:
      required: false
  
  - type: input
    id: linkedin_url
    attributes:
      label: "LinkedIn URL"
      description: "Full LinkedIn profile URL"
      placeholder: "https://www.linkedin.com/in/jane-doe/"
    validations:
      required: false
  
  - type: input
    id: twitter_username
    attributes:
      label: "Twitter/X Username"
      description: "Twitter/X username (without @)"
      placeholder: "janedoe"
    validations:
      required: false
